"""init content db

Revision ID: 6d4b504b9200
Revises:
Create Date: 2026-09-25 20:00:56.195684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d4b504b9200"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["content.categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        schema="content",
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "level",
            sa.Enum("EASY", "MEDIUM", "HARD", name="lesson_level_enum", schema="content"),
            nullable=False,
        ),
        sa.Column(
            "access",
            sa.Enum("PUBLIC", "VIP", name="lesson_access_enum", schema="content"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PENDING", "PUBLISHED", name="lesson_status_enum", schema="content"),
            nullable=False,
        ),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["content.categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("AUDIO", "IMAGE", name="media_kind_enum", schema="content"),
            nullable=False,
        ),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("cdn_url", sa.String(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["content.lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media_assets", schema="content")
    op.drop_table("lessons", schema="content")
    op.drop_table("categories", schema="content")
    # ### end Alembic commands ###
