"""init learning schema

Revision ID: a9072b3502b4
Revises: 
Create Date: 2026-10-08 11:04:40.339079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9072b3502b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Null => top-level comment; set => reply',
               existing_nullable=True,
               schema='learning')
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('comments_lesson_idx'), table_name='comments', schema='learning')
    op.drop_index(op.f('comments_parent_idx'), table_name='comments', schema='learning')
    op.create_index(op.f('ix_learning_comments_lesson_id'), 'comments', ['lesson_id'], unique=False, schema='learning')
    op.create_index(op.f('ix_learning_comments_parent_id'), 'comments', ['parent_id'], unique=False, schema='learning')
    op.alter_column('favorite_lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('favorite_lessons_lesson_idx'), table_name='favorite_lessons', schema='learning')
    op.create_index(op.f('ix_learning_favorite_lessons_lesson_id'), 'favorite_lessons', ['lesson_id'], unique=False, schema='learning')
    op.alter_column('histories', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('histories_user_idx'), table_name='histories', schema='learning')
    op.create_index(op.f('ix_learning_histories_user_id'), 'histories', ['user_id'], unique=False, schema='learning')
    op.alter_column('options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Never serialised to students — stripped in the response schema (backend.md §12)',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='learning')
    op.drop_index(op.f('options_question_idx'), table_name='options', schema='learning')
    op.create_index(op.f('ix_learning_options_question_id'), 'options', ['question_id'], unique=False, schema='learning')
    op.alter_column('questions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'SINGLE_CHOICE'::text"),
               schema='learning')
    op.drop_index(op.f('questions_quiz_idx'), table_name='questions', schema='learning')
    op.create_index(op.f('ix_learning_questions_quiz_id'), 'questions', ['quiz_id'], unique=False, schema='learning')
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('quizzes_lesson_idx'), table_name='quizzes', schema='learning')
    op.create_index(op.f('ix_learning_quizzes_lesson_id'), 'quizzes', ['lesson_id'], unique=False, schema='learning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_quizzes_lesson_id'), table_name='quizzes', schema='learning')
    op.create_index(op.f('quizzes_lesson_idx'), 'quizzes', ['lesson_id'], unique=False, schema='learning')
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('ix_learning_questions_quiz_id'), table_name='questions', schema='learning')
    op.create_index(op.f('questions_quiz_idx'), 'questions', ['quiz_id'], unique=False, schema='learning')
    op.alter_column('questions', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'SINGLE_CHOICE'::text"),
               schema='learning')
    op.drop_index(op.f('ix_learning_options_question_id'), table_name='options', schema='learning')
    op.create_index(op.f('options_question_idx'), 'options', ['question_id'], unique=False, schema='learning')
    op.alter_column('options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               comment='Never serialised to students — stripped in the response schema (backend.md §12)',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='learning')
    op.drop_index(op.f('ix_learning_histories_user_id'), table_name='histories', schema='learning')
    op.create_index(op.f('histories_user_idx'), 'histories', ['user_id'], unique=False, schema='learning')
    op.alter_column('histories', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('ix_learning_favorite_lessons_lesson_id'), table_name='favorite_lessons', schema='learning')
    op.create_index(op.f('favorite_lessons_lesson_idx'), 'favorite_lessons', ['lesson_id'], unique=False, schema='learning')
    op.alter_column('favorite_lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.drop_index(op.f('ix_learning_comments_parent_id'), table_name='comments', schema='learning')
    op.drop_index(op.f('ix_learning_comments_lesson_id'), table_name='comments', schema='learning')
    op.create_index(op.f('comments_parent_idx'), 'comments', ['parent_id'], unique=False, schema='learning')
    op.create_index(op.f('comments_lesson_idx'), 'comments', ['lesson_id'], unique=False, schema='learning')
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='learning')
    op.alter_column('comments', 'parent_id',
               existing_type=sa.UUID(),
               comment='Null => top-level comment; set => reply',
               existing_nullable=True,
               schema='learning')
    # ### end Alembic commands ###
