  /**
 * Design/tailwind.config.mobile.js — Mobile design tokens (NativeWind v4)
 *
 * Source of truth: ../design-system.md. Mirrors tokens.css for web — keep
 * both in sync when a token changes.
 *
 * Setup: once the Expo app exists, copy `theme.extend` below into
 * Mobile/tailwind.config.js (generated by `npx expo customize tailwind.config.js`
 * / the NativeWind setup step). Keep Mobile's own `content` globs.
 *
 * Dark mode: NativeWind's `dark:` variant follows the system color scheme
 * (same mental model as Tailwind's `dark:` on web), but does NOT read CSS
 * variables — a component must pair each token with its `-dark` sibling
 * explicitly, e.g.:
 *   <View className="bg-background dark:bg-background-dark">
 *   <Text className="text-text dark:text-text-dark">
 */
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: "#4f46e5",
        "primary-hover": "#4338ca",
        "primary-foreground": "#ffffff",
        "primary-dark": "#818cf8",
        "primary-hover-dark": "#a5b4fc",
        "primary-foreground-dark": "#1e1b4b",

        secondary: "#f59e0b", // VIP / reward accent — not a generic CTA color
        "secondary-foreground": "#1c1917",
        "secondary-dark": "#fbbf24",
        "secondary-foreground-dark": "#1c1917",

        success: "#16a34a",
        "success-foreground": "#ffffff",
        "success-dark": "#4ade80",
        "success-foreground-dark": "#052e16",

        danger: "#dc2626",
        "danger-foreground": "#ffffff",
        "danger-dark": "#f87171",
        "danger-foreground-dark": "#450a0a",

        warning: "#d97706",
        "warning-foreground": "#1c1917",
        "warning-dark": "#fbbf24",
        "warning-foreground-dark": "#451a03",

        info: "#0284c7",
        "info-foreground": "#ffffff",
        "info-dark": "#38bdf8",
        "info-foreground-dark": "#082f49",

        background: "#ffffff",
        "background-dark": "#0b1120",
        surface: "#f8fafc",
        "surface-dark": "#0f172a",
        "surface-2": "#f1f5f9",
        "surface-2-dark": "#1e293b",
        border: "#e2e8f0",
        "border-dark": "#334155",
        text: "#0f172a",
        "text-dark": "#f1f5f9",
        "text-muted": "#64748b",
        "text-muted-dark": "#94a3b8",
        ring: "#4f46e5",
        "ring-dark": "#818cf8",
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "16px",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter"], // register via @expo-google-fonts/inter in _layout.tsx
      },
    },
  },
};
